# Tiny Tales 6 Dataset Configuration
# Short stories dataset for training/fine-tuning

key: tiny_tales_6_v1
name: tiny_tales_6

# Train/validation split ratios (must sum to 1.0)
train_split: 0.9
validation_split: 0.1

# Random seed for reproducibility
random_seed: 42

# Dataset slices
slices:
  - key: tiny_tales_main
    local: "tiny-tales-6.jsonl"  # Local JSONL file in project root
    sampling: random              # Randomly shuffle the data
